---

- hosts: all
  become: true
  tasks:

  - name: install updates (Redhat)
    tags: always 
    ansible.builtin.dnf:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "Red Hat Enterprise Linux"


  - name: install updates (Ubuntu)
    tags: always 
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
   


- hosts: web_servers
  become: true
  tasks:

    - name: install httpd and php for Redhat servers
      tags: redhat, httpd, php
      ansible.builtin.dnf:
        name: 
          - httpd
          - php
          - openssl 
        state: latest
      when: ansible_distribution == "RedHat"



    - name: install apache and php for Ubuntu servers 
      tags: ubuntu, apache2
      apt:
        name:
          - apache2
          - libapache2-mod-phpi
          - openssl
        state: latest
      when: ansible_distribution == "Ubuntu"

                                                                                          


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb for Redhat servers
    tags: redhat, db, mariadb
    ansible.builtin.dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "RedHat"



  - name: install mariadb for Ubuntu servers
    tags: ubuntu, db, mariadb
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
