---

- hosts: all
  become: true
  tasks:

    - name: update repository index
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd 
        state: latest 
  
    - name: add php support for apache
      ansible.builtin.dnf:
        name: php
        state: latest
