---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (Redhat)
    tags: always 
    ansible.builtin.dnf:
       update_cache: yes
    changed_when: false
    when: ansible_distribution == "Redhat"


  - name: update repo cache (Ubuntu)
    tags: always 
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"


       
- hosts: all 
  become: true
  roles: 
    - base


- hosts: web_servers
  become: true
  roles:
    - web_servers


- hosts: file_servers
  become: true
  roles:
    - file_servers


- hosts: db_servers
  become: true
  roles:
    - db_servers
 
